# Generated by Django 4.0 on 2021-12-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApplication', '0002_remove_employee_email_remove_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
