# Generated by Django 4.0 on 2021-12-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApplication', '0003_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkOut',
            field=models.DateTimeField(null=True),
        ),
    ]
