# Generated by Django 4.0 on 2021-12-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrApplication', '0004_alter_attendance_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacationDate', models.DateTimeField()),
                ('reason', models.CharField(max_length=350)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrApplication.employee')),
            ],
        ),
    ]
