# Generated by Django 4.0 on 2022-01-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrApplication', '0005_vacation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='checkIn',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='checkOut',
            new_name='check_out',
        ),
    ]
