# Generated by Django 4.0 on 2022-01-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApplication', '0007_rename_vacationdate_vacation_vacation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hour_rate',
            field=models.FloatField(null=True),
        ),
    ]
